# Generated by Django 5.1.5 on 2026-05-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_premium', models.BooleanField(default=False)),
                ('subscription_type', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=32)),
                ('subscription_expires', models.DateTimeField(blank=True, null=True)),
                ('daily_generation_limit', models.PositiveIntegerField(default=3)),
                ('provider', models.CharField(blank=True, max_length=32)),
            ],
        ),
    ]
