# Generated by Django 5.1.5 on 2026-05-21 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('category', models.CharField(choices=[('tops', 'Tops'), ('bottoms', 'Bottoms'), ('shoes', 'Shoes'), ('accessories', 'Accessories')], max_length=32)),
                ('subcategory', models.CharField(max_length=64)),
                ('color', models.CharField(max_length=64)),
                ('season', models.CharField(max_length=32)),
                ('style_tags', models.JSONField(blank=True, default=list)),
                ('brand', models.CharField(blank=True, max_length=128)),
                ('formality_level', models.CharField(default='casual', max_length=32)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
