# Generated by Django 5.1.5 on 2026-05-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('occasion', models.CharField(blank=True, max_length=64)),
                ('weather_summary', models.CharField(blank=True, max_length=128)),
                ('result', models.JSONField(default=dict)),
                ('preview_image', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
