# Generated by Django 5.1.5 on 2026-05-21 18:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiGenerationGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('outfit_generation', 'Outfit Generation')], max_length=64)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('success', 'Success'), ('fail', 'Fail')], default='queued', max_length=32)),
                ('prompt', models.TextField()),
                ('weather_summary', models.CharField(blank=True, max_length=128)),
                ('occasion', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AiGenerationTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variant_index', models.PositiveSmallIntegerField(default=0)),
                ('provider_model', models.CharField(default='nano-banana-2', max_length=128)),
                ('provider_task_id', models.CharField(max_length=255, unique=True)),
                ('state', models.CharField(choices=[('waiting', 'Waiting'), ('queuing', 'Queuing'), ('generating', 'Generating'), ('success', 'Success'), ('fail', 'Fail')], default='waiting', max_length=32)),
                ('prompt', models.TextField()),
                ('input_image_urls', models.JSONField(blank=True, default=list)),
                ('result_urls', models.JSONField(blank=True, default=list)),
                ('callback_payload', models.JSONField(blank=True, default=dict)),
                ('fail_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ai.aigenerationgroup')),
            ],
        ),
    ]
